services:
- name: backend-1
  commitSha: 3af7d35282cc07838e7e654d132b46d9297e6ebc
  metadata:
    pr-author: amine7536
    pr-url: https://github.com/amine7536/akpe-backend-1/pull/4
    pr-number: '4'
    created-at: '2026-02-19T10:07:04Z'
    updated-at: '2026-02-19T10:20:57Z'
    vcs.ref.name: feat/sealed-secrets
    cicd.pipeline.run.url: https://github.com/amine7536/akpe-backend-1/actions/runs/22177784275
- name: backend-2
- name: front
