services:
- name: backend-1
  commitSha: 7e6e88dacc879d54e78b1cb5fcb62e4439f941b3
  metadata:
    pr-author: amine7536
    pr-url: https://github.com/amine7536/akpe-backend-1/pull/4
    pr-number: '4'
    created-at: '2026-02-19T10:07:04Z'
    updated-at: '2026-02-19T10:07:04Z'
    vcs.ref.name: feat/sealed-secrets
    cicd.pipeline.run.url: https://github.com/amine7536/akpe-backend-1/actions/runs/22177325984
- name: backend-2
- name: front
