services:
- name: backend-1
  commitSha: 0d2bfe35c4f11b74092c30b5e73a290455fc4467
  metadata:
    pr-author: amine7536
    pr-url: https://github.com/amine7536/akpe-backend-1/pull/4
    pr-number: '4'
    created-at: '2026-02-19T10:07:04Z'
    updated-at: '2026-02-19T10:40:59Z'
    vcs.ref.name: feat/sealed-secrets
    cicd.pipeline.run.url: https://github.com/amine7536/akpe-backend-1/actions/runs/22178432861
- name: backend-2
- name: front
