serviceRepos:
  backend-1: "https://github.com/amine7536/akpe-backend-1.git"
  backend-2: "https://github.com/amine7536/akpe-backend-2.git"
  front:     "https://github.com/amine7536/akpe-front.git"

serviceChart:
  repository: "oci://ghcr.io/amine7536/akpe-charts"
  name: akpe-service
  version: "0.1.0"
