services:
- name: backend-1
  commitSha: 50716bd0f058c4f50602e430ecfffbe893110a89
  metadata:
    pr-author: amine7536
    pr-url: https://github.com/amine7536/akpe-backend-1/pull/3
    pr-number: '3'
    created-at: '2026-02-18T12:11:22Z'
    updated-at: '2026-02-18T19:23:42Z'
    vcs.ref.name: test/preview-e2e
    cicd.pipeline.run.url: https://github.com/amine7536/akpe-backend-1/actions/runs/22154287949
- name: backend-2
  commitSha: 7b3838958424bf1d2e3eba1b999fd434e54e0f1c
  metadata:
    pr-author: amine7536
    pr-url: https://github.com/amine7536/akpe-backend-2/pull/3
    pr-number: '3'
    created-at: '2026-02-18T12:17:59Z'
    updated-at: '2026-02-18T19:23:43Z'
    vcs.ref.name: test/preview-e2e
    cicd.pipeline.run.url: https://github.com/amine7536/akpe-backend-2/actions/runs/22154299391
- name: front
