services:
- name: backend-1
  commitSha: 14a5f7c414edeca2b362cc580fd0bb435515c1b9
  metadata:
    pr-author: amine7536
    pr-url: https://github.com/amine7536/akpe-backend-1/pull/3
    pr-number: '3'
    created-at: '2026-02-18T12:11:22Z'
    updated-at: '2026-02-18T12:11:22Z'
    branch: test/preview-e2e
    workflow-run-url: https://github.com/amine7536/akpe-backend-1/actions/runs/22139200461
- name: backend-2
- name: front
