services:
  - name: backend-1
    commitSha: d8a861119d5cd660d79bbc91882047bc75f2fa9a
    metadata:
      pr-author: amine7536
      pr-url: https://github.com/amine7536/akpe-backend-1/pull/6
      pr-number: '6'
      created-at: '2026-02-20T18:08:33Z'
      updated-at: '2026-02-20T18:41:22Z'
      vcs.ref.name: test/preview-feedback
      cicd.pipeline.run.url: https://github.com/amine7536/akpe-backend-1/actions/runs/22236572403
  - name: backend-2
    commitSha: 169cfdd999825d9745e9fe0396ad9a551fcc7ee2
    metadata:
      pr-author: amine7536
      pr-url: https://github.com/amine7536/akpe-backend-2/pull/5
      pr-number: '5'
      created-at: '2026-02-20T18:09:04Z'
      updated-at: '2026-02-20T18:41:23Z'
      vcs.ref.name: test/preview-feedback
      cicd.pipeline.run.url: https://github.com/amine7536/akpe-backend-2/actions/runs/22236573763
  - name: front
    commitSha: 2d82b2d49007dc00ffa00e1c8024200a59c23d50
    metadata:
      pr-author: amine7536
      pr-url: https://github.com/amine7536/akpe-front/pull/2
      pr-number: '2'
      created-at: '2026-02-20T18:16:41Z'
      updated-at: '2026-02-20T18:30:48Z'
      vcs.ref.name: test/preview-feedback
      cicd.pipeline.run.url: https://github.com/amine7536/akpe-front/actions/runs/22236221348
