services:
- name: backend-1
- name: backend-2
  commitSha: a561984748f922a49e9106f615da83e99c7d27b2
  metadata:
    pr-author: amine7536
    pr-url: https://github.com/amine7536/akpe-backend-2/pull/4
    pr-number: '4'
    created-at: '2026-02-19T19:06:02Z'
    updated-at: '2026-02-19T19:06:02Z'
    vcs.ref.name: feat/test-preview-env
    cicd.pipeline.run.url: https://github.com/amine7536/akpe-backend-2/actions/runs/22196006925
- name: front
